/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * 操作记录表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActionHistory implements Serializable {

    private static final long serialVersionUID = -1974240025;

    private Integer   id;
    private Integer   axtenalId;
    private Integer   action;
    private String    memo;
    private Timestamp created;
    private Integer   createdBy;
    private Integer   communityId;

    public ActionHistory() {}

    public ActionHistory(ActionHistory value) {
        this.id = value.id;
        this.axtenalId = value.axtenalId;
        this.action = value.action;
        this.memo = value.memo;
        this.created = value.created;
        this.createdBy = value.createdBy;
        this.communityId = value.communityId;
    }

    public ActionHistory(
        Integer   id,
        Integer   axtenalId,
        Integer   action,
        String    memo,
        Timestamp created,
        Integer   createdBy,
        Integer   communityId
    ) {
        this.id = id;
        this.axtenalId = axtenalId;
        this.action = action;
        this.memo = memo;
        this.created = created;
        this.createdBy = createdBy;
        this.communityId = communityId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getAxtenalId() {
        return this.axtenalId;
    }

    public void setAxtenalId(Integer axtenalId) {
        this.axtenalId = axtenalId;
    }

    public Integer getAction() {
        return this.action;
    }

    public void setAction(Integer action) {
        this.action = action;
    }

    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Integer getCommunityId() {
        return this.communityId;
    }

    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActionHistory (");

        sb.append(id);
        sb.append(", ").append(axtenalId);
        sb.append(", ").append(action);
        sb.append(", ").append(memo);
        sb.append(", ").append(created);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(communityId);

        sb.append(")");
        return sb.toString();
    }
}
