/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityUserRecord implements Serializable {

    private static final long serialVersionUID = -29851662;

    private Integer id;
    private Integer activityUserId;
    private Date    recordTime;
    private String  pictures;
    private String  notes;

    public ActivityUserRecord() {}

    public ActivityUserRecord(ActivityUserRecord value) {
        this.id = value.id;
        this.activityUserId = value.activityUserId;
        this.recordTime = value.recordTime;
        this.pictures = value.pictures;
        this.notes = value.notes;
    }

    public ActivityUserRecord(
        Integer id,
        Integer activityUserId,
        Date    recordTime,
        String  pictures,
        String  notes
    ) {
        this.id = id;
        this.activityUserId = activityUserId;
        this.recordTime = recordTime;
        this.pictures = pictures;
        this.notes = notes;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getActivityUserId() {
        return this.activityUserId;
    }

    public void setActivityUserId(Integer activityUserId) {
        this.activityUserId = activityUserId;
    }

    public Date getRecordTime() {
        return this.recordTime;
    }

    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    public String getPictures() {
        return this.pictures;
    }

    public void setPictures(String pictures) {
        this.pictures = pictures;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActivityUserRecord (");

        sb.append(id);
        sb.append(", ").append(activityUserId);
        sb.append(", ").append(recordTime);
        sb.append(", ").append(pictures);
        sb.append(", ").append(notes);

        sb.append(")");
        return sb.toString();
    }
}
