/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 活动相册
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityPhoto implements Serializable {

    private static final long serialVersionUID = 969206909;

    private Integer   id;
    private Integer   activityId;
    private String    picture;
    private String    description;
    private Timestamp created;
    private Integer   createdBy;
    private String    axtenalUrl;
    private Integer   browseCount;

    public ActivityPhoto() {}

    public ActivityPhoto(ActivityPhoto value) {
        this.id = value.id;
        this.activityId = value.activityId;
        this.picture = value.picture;
        this.description = value.description;
        this.created = value.created;
        this.createdBy = value.createdBy;
        this.axtenalUrl = value.axtenalUrl;
        this.browseCount = value.browseCount;
    }

    public ActivityPhoto(
        Integer   id,
        Integer   activityId,
        String    picture,
        String    description,
        Timestamp created,
        Integer   createdBy,
        String    axtenalUrl,
        Integer   browseCount
    ) {
        this.id = id;
        this.activityId = activityId;
        this.picture = picture;
        this.description = description;
        this.created = created;
        this.createdBy = createdBy;
        this.axtenalUrl = axtenalUrl;
        this.browseCount = browseCount;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getActivityId() {
        return this.activityId;
    }

    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    public String getPicture() {
        return this.picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public String getAxtenalUrl() {
        return this.axtenalUrl;
    }

    public void setAxtenalUrl(String axtenalUrl) {
        this.axtenalUrl = axtenalUrl;
    }

    public Integer getBrowseCount() {
        return this.browseCount;
    }

    public void setBrowseCount(Integer browseCount) {
        this.browseCount = browseCount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActivityPhoto (");

        sb.append(id);
        sb.append(", ").append(activityId);
        sb.append(", ").append(picture);
        sb.append(", ").append(description);
        sb.append(", ").append(created);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(axtenalUrl);
        sb.append(", ").append(browseCount);

        sb.append(")");
        return sb.toString();
    }
}
