/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 参与活动人
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityUser implements Serializable {

    private static final long serialVersionUID = 592219239;

    private Integer    id;
    private Integer    userId;
    private Integer    activityId;
    private Integer    activityTicketId;
    private Timestamp  created;
    private Integer    createdBy;
    private Timestamp  attendTime;
    private Timestamp  checkInTime;
    private String     realName;
    private String     mobile;
    private String     otherInfo;
    private BigDecimal price;
    private Integer    score;
    private Timestamp  modified;
    private Integer    modifiedBy;
    private Integer    status;

    public ActivityUser() {}

    public ActivityUser(ActivityUser value) {
        this.id = value.id;
        this.userId = value.userId;
        this.activityId = value.activityId;
        this.activityTicketId = value.activityTicketId;
        this.created = value.created;
        this.createdBy = value.createdBy;
        this.attendTime = value.attendTime;
        this.checkInTime = value.checkInTime;
        this.realName = value.realName;
        this.mobile = value.mobile;
        this.otherInfo = value.otherInfo;
        this.price = value.price;
        this.score = value.score;
        this.modified = value.modified;
        this.modifiedBy = value.modifiedBy;
        this.status = value.status;
    }

    public ActivityUser(
        Integer    id,
        Integer    userId,
        Integer    activityId,
        Integer    activityTicketId,
        Timestamp  created,
        Integer    createdBy,
        Timestamp  attendTime,
        Timestamp  checkInTime,
        String     realName,
        String     mobile,
        String     otherInfo,
        BigDecimal price,
        Integer    score,
        Timestamp  modified,
        Integer    modifiedBy,
        Integer    status
    ) {
        this.id = id;
        this.userId = userId;
        this.activityId = activityId;
        this.activityTicketId = activityTicketId;
        this.created = created;
        this.createdBy = createdBy;
        this.attendTime = attendTime;
        this.checkInTime = checkInTime;
        this.realName = realName;
        this.mobile = mobile;
        this.otherInfo = otherInfo;
        this.price = price;
        this.score = score;
        this.modified = modified;
        this.modifiedBy = modifiedBy;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getActivityId() {
        return this.activityId;
    }

    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    public Integer getActivityTicketId() {
        return this.activityTicketId;
    }

    public void setActivityTicketId(Integer activityTicketId) {
        this.activityTicketId = activityTicketId;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getAttendTime() {
        return this.attendTime;
    }

    public void setAttendTime(Timestamp attendTime) {
        this.attendTime = attendTime;
    }

    public Timestamp getCheckInTime() {
        return this.checkInTime;
    }

    public void setCheckInTime(Timestamp checkInTime) {
        this.checkInTime = checkInTime;
    }

    public String getRealName() {
        return this.realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getOtherInfo() {
        return this.otherInfo;
    }

    public void setOtherInfo(String otherInfo) {
        this.otherInfo = otherInfo;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Integer getScore() {
        return this.score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public Timestamp getModified() {
        return this.modified;
    }

    public void setModified(Timestamp modified) {
        this.modified = modified;
    }

    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActivityUser (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(activityId);
        sb.append(", ").append(activityTicketId);
        sb.append(", ").append(created);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(attendTime);
        sb.append(", ").append(checkInTime);
        sb.append(", ").append(realName);
        sb.append(", ").append(mobile);
        sb.append(", ").append(otherInfo);
        sb.append(", ").append(price);
        sb.append(", ").append(score);
        sb.append(", ").append(modified);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
