/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * 活动门票
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityTicket implements Serializable {

    private static final long serialVersionUID = 812224607;

    private Integer    id;
    private Integer    activityId;
    private String     title;
    private String     memo;
    private BigDecimal price;
    private Integer    count;
    private Integer    userLevel;
    private Integer    score;

    public ActivityTicket() {}

    public ActivityTicket(ActivityTicket value) {
        this.id = value.id;
        this.activityId = value.activityId;
        this.title = value.title;
        this.memo = value.memo;
        this.price = value.price;
        this.count = value.count;
        this.userLevel = value.userLevel;
        this.score = value.score;
    }

    public ActivityTicket(
        Integer    id,
        Integer    activityId,
        String     title,
        String     memo,
        BigDecimal price,
        Integer    count,
        Integer    userLevel,
        Integer    score
    ) {
        this.id = id;
        this.activityId = activityId;
        this.title = title;
        this.memo = memo;
        this.price = price;
        this.count = count;
        this.userLevel = userLevel;
        this.score = score;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getActivityId() {
        return this.activityId;
    }

    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Integer getCount() {
        return this.count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Integer getUserLevel() {
        return this.userLevel;
    }

    public void setUserLevel(Integer userLevel) {
        this.userLevel = userLevel;
    }

    public Integer getScore() {
        return this.score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActivityTicket (");

        sb.append(id);
        sb.append(", ").append(activityId);
        sb.append(", ").append(title);
        sb.append(", ").append(memo);
        sb.append(", ").append(price);
        sb.append(", ").append(count);
        sb.append(", ").append(userLevel);
        sb.append(", ").append(score);

        sb.append(")");
        return sb.toString();
    }
}
