/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivitySms implements Serializable {

    private static final long serialVersionUID = 1273211488;

    private Integer   id;
    private Integer   activityId;
    private String    templateCode;
    private String    templateName;
    private String    messageContent;
    private Timestamp sendTime;
    private Integer   sendUserId;
    private String    sendResultCode;
    private String    sendResultDesc;

    public ActivitySms() {}

    public ActivitySms(ActivitySms value) {
        this.id = value.id;
        this.activityId = value.activityId;
        this.templateCode = value.templateCode;
        this.templateName = value.templateName;
        this.messageContent = value.messageContent;
        this.sendTime = value.sendTime;
        this.sendUserId = value.sendUserId;
        this.sendResultCode = value.sendResultCode;
        this.sendResultDesc = value.sendResultDesc;
    }

    public ActivitySms(
        Integer   id,
        Integer   activityId,
        String    templateCode,
        String    templateName,
        String    messageContent,
        Timestamp sendTime,
        Integer   sendUserId,
        String    sendResultCode,
        String    sendResultDesc
    ) {
        this.id = id;
        this.activityId = activityId;
        this.templateCode = templateCode;
        this.templateName = templateName;
        this.messageContent = messageContent;
        this.sendTime = sendTime;
        this.sendUserId = sendUserId;
        this.sendResultCode = sendResultCode;
        this.sendResultDesc = sendResultDesc;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getActivityId() {
        return this.activityId;
    }

    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    public String getTemplateCode() {
        return this.templateCode;
    }

    public void setTemplateCode(String templateCode) {
        this.templateCode = templateCode;
    }

    public String getTemplateName() {
        return this.templateName;
    }

    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    public String getMessageContent() {
        return this.messageContent;
    }

    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    public Timestamp getSendTime() {
        return this.sendTime;
    }

    public void setSendTime(Timestamp sendTime) {
        this.sendTime = sendTime;
    }

    public Integer getSendUserId() {
        return this.sendUserId;
    }

    public void setSendUserId(Integer sendUserId) {
        this.sendUserId = sendUserId;
    }

    public String getSendResultCode() {
        return this.sendResultCode;
    }

    public void setSendResultCode(String sendResultCode) {
        this.sendResultCode = sendResultCode;
    }

    public String getSendResultDesc() {
        return this.sendResultDesc;
    }

    public void setSendResultDesc(String sendResultDesc) {
        this.sendResultDesc = sendResultDesc;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActivitySms (");

        sb.append(id);
        sb.append(", ").append(activityId);
        sb.append(", ").append(templateCode);
        sb.append(", ").append(templateName);
        sb.append(", ").append(messageContent);
        sb.append(", ").append(sendTime);
        sb.append(", ").append(sendUserId);
        sb.append(", ").append(sendResultCode);
        sb.append(", ").append(sendResultDesc);

        sb.append(")");
        return sb.toString();
    }
}
