/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 文章 内容发布
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Article implements Serializable {

    private static final long serialVersionUID = 1592078688;

    private Integer   id;
    private Integer   communityId;
    private String    title;
    private String    summary;
    private Integer   category;
    private String    body;
    private Integer   status;
    private Timestamp publishTime;
    private String    avatar;
    private String    unit;
    private Timestamp created;
    private Integer   createdBy;
    private Timestamp modified;
    private Integer   modifiedBy;

    public Article() {}

    public Article(Article value) {
        this.id = value.id;
        this.communityId = value.communityId;
        this.title = value.title;
        this.summary = value.summary;
        this.category = value.category;
        this.body = value.body;
        this.status = value.status;
        this.publishTime = value.publishTime;
        this.avatar = value.avatar;
        this.unit = value.unit;
        this.created = value.created;
        this.createdBy = value.createdBy;
        this.modified = value.modified;
        this.modifiedBy = value.modifiedBy;
    }

    public Article(
        Integer   id,
        Integer   communityId,
        String    title,
        String    summary,
        Integer   category,
        String    body,
        Integer   status,
        Timestamp publishTime,
        String    avatar,
        String    unit,
        Timestamp created,
        Integer   createdBy,
        Timestamp modified,
        Integer   modifiedBy
    ) {
        this.id = id;
        this.communityId = communityId;
        this.title = title;
        this.summary = summary;
        this.category = category;
        this.body = body;
        this.status = status;
        this.publishTime = publishTime;
        this.avatar = avatar;
        this.unit = unit;
        this.created = created;
        this.createdBy = createdBy;
        this.modified = modified;
        this.modifiedBy = modifiedBy;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCommunityId() {
        return this.communityId;
    }

    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSummary() {
        return this.summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public Integer getCategory() {
        return this.category;
    }

    public void setCategory(Integer category) {
        this.category = category;
    }

    public String getBody() {
        return this.body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Timestamp getPublishTime() {
        return this.publishTime;
    }

    public void setPublishTime(Timestamp publishTime) {
        this.publishTime = publishTime;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getModified() {
        return this.modified;
    }

    public void setModified(Timestamp modified) {
        this.modified = modified;
    }

    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Article (");

        sb.append(id);
        sb.append(", ").append(communityId);
        sb.append(", ").append(title);
        sb.append(", ").append(summary);
        sb.append(", ").append(category);
        sb.append(", ").append(body);
        sb.append(", ").append(status);
        sb.append(", ").append(publishTime);
        sb.append(", ").append(avatar);
        sb.append(", ").append(unit);
        sb.append(", ").append(created);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(modified);
        sb.append(", ").append(modifiedBy);

        sb.append(")");
        return sb.toString();
    }
}
