/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * 社团成员
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommunityUser implements Serializable {

    private static final long serialVersionUID = -739952495;

    private Integer   id;
    private Integer   communityId;
    private Integer   userId;
    private String    role;
    private Timestamp created;
    private Integer   level;
    private Boolean   isBlack;

    public CommunityUser() {}

    public CommunityUser(CommunityUser value) {
        this.id = value.id;
        this.communityId = value.communityId;
        this.userId = value.userId;
        this.role = value.role;
        this.created = value.created;
        this.level = value.level;
        this.isBlack = value.isBlack;
    }

    public CommunityUser(
        Integer   id,
        Integer   communityId,
        Integer   userId,
        String    role,
        Timestamp created,
        Integer   level,
        Boolean   isBlack
    ) {
        this.id = id;
        this.communityId = communityId;
        this.userId = userId;
        this.role = role;
        this.created = created;
        this.level = level;
        this.isBlack = isBlack;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCommunityId() {
        return this.communityId;
    }

    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Integer getLevel() {
        return this.level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Boolean getIsBlack() {
        return this.isBlack;
    }

    public void setIsBlack(Boolean isBlack) {
        this.isBlack = isBlack;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CommunityUser (");

        sb.append(id);
        sb.append(", ").append(communityId);
        sb.append(", ").append(userId);
        sb.append(", ").append(role);
        sb.append(", ").append(created);
        sb.append(", ").append(level);
        sb.append(", ").append(isBlack);

        sb.append(")");
        return sb.toString();
    }
}
