/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 单位公司
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Company implements Serializable {

    private static final long serialVersionUID = 1077422475;

    private Integer   id;
    private String    title;
    private Integer   ownerId;
    private Boolean   isReal;
    private String    fax;
    private String    tel;
    private String    address;
    private Timestamp realTime;
    private Timestamp created;

    public Company() {}

    public Company(Company value) {
        this.id = value.id;
        this.title = value.title;
        this.ownerId = value.ownerId;
        this.isReal = value.isReal;
        this.fax = value.fax;
        this.tel = value.tel;
        this.address = value.address;
        this.realTime = value.realTime;
        this.created = value.created;
    }

    public Company(
        Integer   id,
        String    title,
        Integer   ownerId,
        Boolean   isReal,
        String    fax,
        String    tel,
        String    address,
        Timestamp realTime,
        Timestamp created
    ) {
        this.id = id;
        this.title = title;
        this.ownerId = ownerId;
        this.isReal = isReal;
        this.fax = fax;
        this.tel = tel;
        this.address = address;
        this.realTime = realTime;
        this.created = created;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getOwnerId() {
        return this.ownerId;
    }

    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    public Boolean getIsReal() {
        return this.isReal;
    }

    public void setIsReal(Boolean isReal) {
        this.isReal = isReal;
    }

    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getTel() {
        return this.tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Timestamp getRealTime() {
        return this.realTime;
    }

    public void setRealTime(Timestamp realTime) {
        this.realTime = realTime;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Company (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(isReal);
        sb.append(", ").append(fax);
        sb.append(", ").append(tel);
        sb.append(", ").append(address);
        sb.append(", ").append(realTime);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
}
