/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PayOrder implements Serializable {

    private static final long serialVersionUID = 989990977;

    private Integer    id;
    private Integer    userId;
    private Integer    activityId;
    private Integer    activityTicketId;
    private String     title;
    private String     body;
    private BigDecimal price;
    private Timestamp  payTime;
    private Timestamp  cancelTime;
    private Integer    status;
    private String     extenalId;
    private Timestamp  created;
    private String     otherInfo;
    private String     refundTradeNo;
    private Timestamp  refundTime;
    private Integer    refundStatus;
    private Integer    communityId;

    public PayOrder() {}

    public PayOrder(PayOrder value) {
        this.id = value.id;
        this.userId = value.userId;
        this.activityId = value.activityId;
        this.activityTicketId = value.activityTicketId;
        this.title = value.title;
        this.body = value.body;
        this.price = value.price;
        this.payTime = value.payTime;
        this.cancelTime = value.cancelTime;
        this.status = value.status;
        this.extenalId = value.extenalId;
        this.created = value.created;
        this.otherInfo = value.otherInfo;
        this.refundTradeNo = value.refundTradeNo;
        this.refundTime = value.refundTime;
        this.refundStatus = value.refundStatus;
        this.communityId = value.communityId;
    }

    public PayOrder(
        Integer    id,
        Integer    userId,
        Integer    activityId,
        Integer    activityTicketId,
        String     title,
        String     body,
        BigDecimal price,
        Timestamp  payTime,
        Timestamp  cancelTime,
        Integer    status,
        String     extenalId,
        Timestamp  created,
        String     otherInfo,
        String     refundTradeNo,
        Timestamp  refundTime,
        Integer    refundStatus,
        Integer    communityId
    ) {
        this.id = id;
        this.userId = userId;
        this.activityId = activityId;
        this.activityTicketId = activityTicketId;
        this.title = title;
        this.body = body;
        this.price = price;
        this.payTime = payTime;
        this.cancelTime = cancelTime;
        this.status = status;
        this.extenalId = extenalId;
        this.created = created;
        this.otherInfo = otherInfo;
        this.refundTradeNo = refundTradeNo;
        this.refundTime = refundTime;
        this.refundStatus = refundStatus;
        this.communityId = communityId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getActivityId() {
        return this.activityId;
    }

    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    public Integer getActivityTicketId() {
        return this.activityTicketId;
    }

    public void setActivityTicketId(Integer activityTicketId) {
        this.activityTicketId = activityTicketId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBody() {
        return this.body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Timestamp getPayTime() {
        return this.payTime;
    }

    public void setPayTime(Timestamp payTime) {
        this.payTime = payTime;
    }

    public Timestamp getCancelTime() {
        return this.cancelTime;
    }

    public void setCancelTime(Timestamp cancelTime) {
        this.cancelTime = cancelTime;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getExtenalId() {
        return this.extenalId;
    }

    public void setExtenalId(String extenalId) {
        this.extenalId = extenalId;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public String getOtherInfo() {
        return this.otherInfo;
    }

    public void setOtherInfo(String otherInfo) {
        this.otherInfo = otherInfo;
    }

    public String getRefundTradeNo() {
        return this.refundTradeNo;
    }

    public void setRefundTradeNo(String refundTradeNo) {
        this.refundTradeNo = refundTradeNo;
    }

    public Timestamp getRefundTime() {
        return this.refundTime;
    }

    public void setRefundTime(Timestamp refundTime) {
        this.refundTime = refundTime;
    }

    public Integer getRefundStatus() {
        return this.refundStatus;
    }

    public void setRefundStatus(Integer refundStatus) {
        this.refundStatus = refundStatus;
    }

    public Integer getCommunityId() {
        return this.communityId;
    }

    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PayOrder (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(activityId);
        sb.append(", ").append(activityTicketId);
        sb.append(", ").append(title);
        sb.append(", ").append(body);
        sb.append(", ").append(price);
        sb.append(", ").append(payTime);
        sb.append(", ").append(cancelTime);
        sb.append(", ").append(status);
        sb.append(", ").append(extenalId);
        sb.append(", ").append(created);
        sb.append(", ").append(otherInfo);
        sb.append(", ").append(refundTradeNo);
        sb.append(", ").append(refundTime);
        sb.append(", ").append(refundStatus);
        sb.append(", ").append(communityId);

        sb.append(")");
        return sb.toString();
    }
}
