/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * 海报表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Poster implements Serializable {

    private static final long serialVersionUID = -2115718479;

    private Integer   id;
    private String    title;
    private String    avatar;
    private String    mobileAvatar;
    private String    link;
    private Integer   activityId;
    private Timestamp created;
    private String    posterType;
    private Boolean   show;
    private Integer   sequence;

    public Poster() {}

    public Poster(Poster value) {
        this.id = value.id;
        this.title = value.title;
        this.avatar = value.avatar;
        this.mobileAvatar = value.mobileAvatar;
        this.link = value.link;
        this.activityId = value.activityId;
        this.created = value.created;
        this.posterType = value.posterType;
        this.show = value.show;
        this.sequence = value.sequence;
    }

    public Poster(
        Integer   id,
        String    title,
        String    avatar,
        String    mobileAvatar,
        String    link,
        Integer   activityId,
        Timestamp created,
        String    posterType,
        Boolean   show,
        Integer   sequence
    ) {
        this.id = id;
        this.title = title;
        this.avatar = avatar;
        this.mobileAvatar = mobileAvatar;
        this.link = link;
        this.activityId = activityId;
        this.created = created;
        this.posterType = posterType;
        this.show = show;
        this.sequence = sequence;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getMobileAvatar() {
        return this.mobileAvatar;
    }

    public void setMobileAvatar(String mobileAvatar) {
        this.mobileAvatar = mobileAvatar;
    }

    public String getLink() {
        return this.link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public Integer getActivityId() {
        return this.activityId;
    }

    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public String getPosterType() {
        return this.posterType;
    }

    public void setPosterType(String posterType) {
        this.posterType = posterType;
    }

    public Boolean getShow() {
        return this.show;
    }

    public void setShow(Boolean show) {
        this.show = show;
    }

    public Integer getSequence() {
        return this.sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Poster (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(avatar);
        sb.append(", ").append(mobileAvatar);
        sb.append(", ").append(link);
        sb.append(", ").append(activityId);
        sb.append(", ").append(created);
        sb.append(", ").append(posterType);
        sb.append(", ").append(show);
        sb.append(", ").append(sequence);

        sb.append(")");
        return sb.toString();
    }
}
