/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 积分历史
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScoreHistory implements Serializable {

    private static final long serialVersionUID = 1683489171;

    private Integer   id;
    private Integer   score;
    private Integer   userId;
    private Integer   activityId;
    private String    memo;
    private Timestamp created;
    private Integer   communityId;

    public ScoreHistory() {}

    public ScoreHistory(ScoreHistory value) {
        this.id = value.id;
        this.score = value.score;
        this.userId = value.userId;
        this.activityId = value.activityId;
        this.memo = value.memo;
        this.created = value.created;
        this.communityId = value.communityId;
    }

    public ScoreHistory(
        Integer   id,
        Integer   score,
        Integer   userId,
        Integer   activityId,
        String    memo,
        Timestamp created,
        Integer   communityId
    ) {
        this.id = id;
        this.score = score;
        this.userId = userId;
        this.activityId = activityId;
        this.memo = memo;
        this.created = created;
        this.communityId = communityId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getScore() {
        return this.score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getActivityId() {
        return this.activityId;
    }

    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Integer getCommunityId() {
        return this.communityId;
    }

    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ScoreHistory (");

        sb.append(id);
        sb.append(", ").append(score);
        sb.append(", ").append(userId);
        sb.append(", ").append(activityId);
        sb.append(", ").append(memo);
        sb.append(", ").append(created);
        sb.append(", ").append(communityId);

        sb.append(")");
        return sb.toString();
    }
}
