/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 训练营
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrainingCamp implements Serializable {

    private static final long serialVersionUID = -73662793;

    private Integer   id;
    private String    campName;
    private String    campNote;
    private Timestamp modified;
    private Integer   modifiedBy;
    private Integer   communityId;

    public TrainingCamp() {}

    public TrainingCamp(TrainingCamp value) {
        this.id = value.id;
        this.campName = value.campName;
        this.campNote = value.campNote;
        this.modified = value.modified;
        this.modifiedBy = value.modifiedBy;
        this.communityId = value.communityId;
    }

    public TrainingCamp(
        Integer   id,
        String    campName,
        String    campNote,
        Timestamp modified,
        Integer   modifiedBy,
        Integer   communityId
    ) {
        this.id = id;
        this.campName = campName;
        this.campNote = campNote;
        this.modified = modified;
        this.modifiedBy = modifiedBy;
        this.communityId = communityId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCampName() {
        return this.campName;
    }

    public void setCampName(String campName) {
        this.campName = campName;
    }

    public String getCampNote() {
        return this.campNote;
    }

    public void setCampNote(String campNote) {
        this.campNote = campNote;
    }

    public Timestamp getModified() {
        return this.modified;
    }

    public void setModified(Timestamp modified) {
        this.modified = modified;
    }

    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Integer getCommunityId() {
        return this.communityId;
    }

    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TrainingCamp (");

        sb.append(id);
        sb.append(", ").append(campName);
        sb.append(", ").append(campNote);
        sb.append(", ").append(modified);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(communityId);

        sb.append(")");
        return sb.toString();
    }
}
