/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * 用户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -49702778;

    private Integer   id;
    private String    username;
    private String    displayname;
    private String    password;
    private String    role;
    private Boolean   enabled;
    private Integer   gender;
    private Timestamp created;
    private Integer   level;
    private String    idCard;
    private String    realName;
    private Timestamp realTime;
    private Boolean   isReal;
    private String    openId;
    private String    avatar;
    private String    email;
    private String    workCompany;
    private Boolean   isParty;
    private String    address;
    private String    bloodType;
    private String    clothingSize;
    private String    occupation;
    private String    emergencyContactName;
    private String    emergencyContactMobile;
    private String    wechatId;
    private String    unionId;
    private String    nickName;
    private String mobile;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.username = value.username;
        this.displayname = value.displayname;
        this.password = value.password;
        this.role = value.role;
        this.enabled = value.enabled;
        this.gender = value.gender;
        this.created = value.created;
        this.level = value.level;
        this.idCard = value.idCard;
        this.realName = value.realName;
        this.realTime = value.realTime;
        this.isReal = value.isReal;
        this.openId = value.openId;
        this.avatar = value.avatar;
        this.email = value.email;
        this.workCompany = value.workCompany;
        this.isParty = value.isParty;
        this.address = value.address;
        this.bloodType = value.bloodType;
        this.clothingSize = value.clothingSize;
        this.occupation = value.occupation;
        this.emergencyContactName = value.emergencyContactName;
        this.emergencyContactMobile = value.emergencyContactMobile;
        this.wechatId = value.wechatId;
        this.unionId = value.unionId;
        this.nickName = value.nickName;
        this.mobile = value.mobile;
    }

    public User(
            Integer   id,
            String    username,
            String    displayname,
            String    password,
            String    role,
            Boolean   enabled,
            Integer   gender,
            Timestamp created,
            Integer   level,
            String    idCard,
            String    realName,
            Timestamp realTime,
            Boolean   isReal,
            String    openId,
            String    avatar,
            String    email,
            String    workCompany,
            Boolean   isParty,
            String    address,
            String    bloodType,
            String    clothingSize,
            String    occupation,
            String    emergencyContactName,
            String    emergencyContactMobile,
            String    wechatId,
            String    unionId,
            String nickName,
            String mobile
    ) {
        this.id = id;
        this.username = username;
        this.displayname = displayname;
        this.password = password;
        this.role = role;
        this.enabled = enabled;
        this.gender = gender;
        this.created = created;
        this.level = level;
        this.idCard = idCard;
        this.realName = realName;
        this.realTime = realTime;
        this.isReal = isReal;
        this.openId = openId;
        this.avatar = avatar;
        this.email = email;
        this.workCompany = workCompany;
        this.isParty = isParty;
        this.address = address;
        this.bloodType = bloodType;
        this.clothingSize = clothingSize;
        this.occupation = occupation;
        this.emergencyContactName = emergencyContactName;
        this.emergencyContactMobile = emergencyContactMobile;
        this.wechatId = wechatId;
        this.unionId = unionId;
        this.nickName = nickName;
        this.mobile = mobile;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getDisplayname() {
        return this.displayname;
    }

    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Integer getGender() {
        return this.gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Integer getLevel() {
        return this.level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public String getIdCard() {
        return this.idCard;
    }

    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    public String getRealName() {
        return this.realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public Timestamp getRealTime() {
        return this.realTime;
    }

    public void setRealTime(Timestamp realTime) {
        this.realTime = realTime;
    }

    public Boolean getIsReal() {
        return this.isReal;
    }

    public void setIsReal(Boolean isReal) {
        this.isReal = isReal;
    }

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getWorkCompany() {
        return this.workCompany;
    }

    public void setWorkCompany(String workCompany) {
        this.workCompany = workCompany;
    }

    public Boolean getIsParty() {
        return this.isParty;
    }

    public void setIsParty(Boolean isParty) {
        this.isParty = isParty;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getBloodType() {
        return this.bloodType;
    }

    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }

    public String getClothingSize() {
        return this.clothingSize;
    }

    public void setClothingSize(String clothingSize) {
        this.clothingSize = clothingSize;
    }

    public String getOccupation() {
        return this.occupation;
    }

    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    public String getEmergencyContactName() {
        return this.emergencyContactName;
    }

    public void setEmergencyContactName(String emergencyContactName) {
        this.emergencyContactName = emergencyContactName;
    }

    public String getEmergencyContactMobile() {
        return this.emergencyContactMobile;
    }

    public void setEmergencyContactMobile(String emergencyContactMobile) {
        this.emergencyContactMobile = emergencyContactMobile;
    }

    public String getWechatId() {
        return this.wechatId;
    }

    public void setWechatId(String wechatId) {
        this.wechatId = wechatId;
    }

    public String getUnionId() {
        return this.unionId;
    }

    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    public String getNickName() {
        return this.nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(displayname);
        sb.append(", ").append(password);
        sb.append(", ").append(role);
        sb.append(", ").append(enabled);
        sb.append(", ").append(gender);
        sb.append(", ").append(created);
        sb.append(", ").append(level);
        sb.append(", ").append(idCard);
        sb.append(", ").append(realName);
        sb.append(", ").append(realTime);
        sb.append(", ").append(isReal);
        sb.append(", ").append(openId);
        sb.append(", ").append(avatar);
        sb.append(", ").append(email);
        sb.append(", ").append(workCompany);
        sb.append(", ").append(isParty);
        sb.append(", ").append(address);
        sb.append(", ").append(bloodType);
        sb.append(", ").append(clothingSize);
        sb.append(", ").append(occupation);
        sb.append(", ").append(emergencyContactName);
        sb.append(", ").append(emergencyContactMobile);
        sb.append(", ").append(wechatId);
        sb.append(", ").append(unionId);
        sb.append(", ").append(nickName);
        sb.append(", ").append(mobile);

        sb.append(")");
        return sb.toString();
    }
}
