/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.records;


import com.kylin.activity.databases.tables.ActivityUser;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 参与活动人
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityUserRecord extends UpdatableRecordImpl<ActivityUserRecord> implements Record18<Integer, Integer, Integer, Integer, Timestamp, Integer, Timestamp, Timestamp, String, String, String, BigDecimal, Integer, Timestamp, Integer, Integer, String, Timestamp> {

    private static final long serialVersionUID = 1895749578;

    /**
     * Setter for <code>activity_user.id</code>. 编号
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>activity_user.id</code>. 编号
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>activity_user.user_id</code>. 用户编号
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>activity_user.user_id</code>. 用户编号
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>activity_user.activity_id</code>. 活动编号
     */
    public void setActivityId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>activity_user.activity_id</code>. 活动编号
     */
    public Integer getActivityId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>activity_user.activity_ticket_id</code>. 活动门票编号
     */
    public void setActivityTicketId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>activity_user.activity_ticket_id</code>. 活动门票编号
     */
    public Integer getActivityTicketId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>activity_user.created</code>. 创建时间
     */
    public void setCreated(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>activity_user.created</code>. 创建时间
     */
    public Timestamp getCreated() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>activity_user.created_by</code>. 创建人
     */
    public void setCreatedBy(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>activity_user.created_by</code>. 创建人
     */
    public Integer getCreatedBy() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>activity_user.attend_time</code>. 报名时间
     */
    public void setAttendTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>activity_user.attend_time</code>. 报名时间
     */
    public Timestamp getAttendTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>activity_user.check_in_time</code>. 签到时间
     */
    public void setCheckInTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>activity_user.check_in_time</code>. 签到时间
     */
    public Timestamp getCheckInTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>activity_user.real_name</code>. 名称
     */
    public void setRealName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>activity_user.real_name</code>. 名称
     */
    public String getRealName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>activity_user.mobile</code>. 联系方式
     */
    public void setMobile(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>activity_user.mobile</code>. 联系方式
     */
    public String getMobile() {
        return (String) get(9);
    }

    /**
     * Setter for <code>activity_user.other_info</code>. 其他信息
     */
    public void setOtherInfo(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>activity_user.other_info</code>. 其他信息
     */
    public String getOtherInfo() {
        return (String) get(10);
    }

    /**
     * Setter for <code>activity_user.price</code>. 报名时的缴费金额
     */
    public void setPrice(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>activity_user.price</code>. 报名时的缴费金额
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>activity_user.score</code>. 报名时的积分抵扣值
     */
    public void setScore(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>activity_user.score</code>. 报名时的积分抵扣值
     */
    public Integer getScore() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>activity_user.modified</code>. 修改时间
     */
    public void setModified(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>activity_user.modified</code>. 修改时间
     */
    public Timestamp getModified() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>activity_user.modified_by</code>. 修改人
     */
    public void setModifiedBy(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>activity_user.modified_by</code>. 修改人
     */
    public Integer getModifiedBy() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>activity_user.status</code>. 中签状态（0-不抽签；1-待抽签，2-中签，3-已申请退费，4-已完成退费，5-未中签）
     */
    public void setStatus(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>activity_user.status</code>. 中签状态（0-不抽签；1-待抽签，2-中签，3-已申请退费，4-已完成退费，5-未中签）
     */
    public Integer getStatus() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>activity_user.after_files</code>. 活动后，上传图片
     */
    public void setAfterFiles(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>activity_user.after_files</code>. 活动后，上传图片
     */
    public String getAfterFiles() {
        return (String) get(16);
    }

    /**
     * Setter for <code>activity_user.after_time</code>. 活动图片上传时间
     */
    public void setAfterTime(Timestamp value) {
        set(17, value);
    }

    /**
     * Getter for <code>activity_user.after_time</code>. 活动图片上传时间
     */
    public Timestamp getAfterTime() {
        return (Timestamp) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Integer, Integer, Integer, Integer, Timestamp, Integer, Timestamp, Timestamp, String, String, String, BigDecimal, Integer, Timestamp, Integer, Integer, String, Timestamp> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Integer, Integer, Integer, Integer, Timestamp, Integer, Timestamp, Timestamp, String, String, String, BigDecimal, Integer, Timestamp, Integer, Integer, String, Timestamp> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ActivityUser.ACTIVITY_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ActivityUser.ACTIVITY_USER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ActivityUser.ACTIVITY_USER.ACTIVITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ActivityUser.ACTIVITY_USER.ACTIVITY_TICKET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return ActivityUser.ACTIVITY_USER.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ActivityUser.ACTIVITY_USER.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return ActivityUser.ACTIVITY_USER.ATTEND_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return ActivityUser.ACTIVITY_USER.CHECK_IN_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ActivityUser.ACTIVITY_USER.REAL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return ActivityUser.ACTIVITY_USER.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return ActivityUser.ACTIVITY_USER.OTHER_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return ActivityUser.ACTIVITY_USER.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return ActivityUser.ACTIVITY_USER.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return ActivityUser.ACTIVITY_USER.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return ActivityUser.ACTIVITY_USER.MODIFIED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field16() {
        return ActivityUser.ACTIVITY_USER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return ActivityUser.ACTIVITY_USER.AFTER_FILES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return ActivityUser.ACTIVITY_USER.AFTER_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getActivityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getActivityTicketId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getAttendTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCheckInTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getRealName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getOtherInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component12() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component15() {
        return getModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component16() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getAfterFiles();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component18() {
        return getAfterTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getActivityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getActivityTicketId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getAttendTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCheckInTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getRealName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getOtherInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value16() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getAfterFiles();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getAfterTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value3(Integer value) {
        setActivityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value4(Integer value) {
        setActivityTicketId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value5(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value6(Integer value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value7(Timestamp value) {
        setAttendTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value8(Timestamp value) {
        setCheckInTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value9(String value) {
        setRealName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value10(String value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value11(String value) {
        setOtherInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value12(BigDecimal value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value13(Integer value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value14(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value15(Integer value) {
        setModifiedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value16(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value17(String value) {
        setAfterFiles(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord value18(Timestamp value) {
        setAfterTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityUserRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5, Integer value6, Timestamp value7, Timestamp value8, String value9, String value10, String value11, BigDecimal value12, Integer value13, Timestamp value14, Integer value15, Integer value16, String value17, Timestamp value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityUserRecord
     */
    public ActivityUserRecord() {
        super(ActivityUser.ACTIVITY_USER);
    }

    /**
     * Create a detached, initialised ActivityUserRecord
     */
    public ActivityUserRecord(Integer id, Integer userId, Integer activityId, Integer activityTicketId, Timestamp created, Integer createdBy, Timestamp attendTime, Timestamp checkInTime, String realName, String mobile, String otherInfo, BigDecimal price, Integer score, Timestamp modified, Integer modifiedBy, Integer status, String afterFiles, Timestamp afterTime) {
        super(ActivityUser.ACTIVITY_USER);

        set(0, id);
        set(1, userId);
        set(2, activityId);
        set(3, activityTicketId);
        set(4, created);
        set(5, createdBy);
        set(6, attendTime);
        set(7, checkInTime);
        set(8, realName);
        set(9, mobile);
        set(10, otherInfo);
        set(11, price);
        set(12, score);
        set(13, modified);
        set(14, modifiedBy);
        set(15, status);
        set(16, afterFiles);
        set(17, afterTime);
    }
}
