/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.records;


import com.kylin.activity.databases.tables.ActionHistory;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActionHistoryRecord extends UpdatableRecordImpl<ActionHistoryRecord> implements Record6<Integer, Integer, Integer, String, Timestamp, Integer> {

    private static final long serialVersionUID = 1491250731;

    /**
     * Setter for <code>activity.action_history.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>activity.action_history.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>activity.action_history.axtenal_id</code>.
     */
    public void setAxtenalId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>activity.action_history.axtenal_id</code>.
     */
    public Integer getAxtenalId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>activity.action_history.action</code>.
     */
    public void setAction(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>activity.action_history.action</code>.
     */
    public Integer getAction() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>activity.action_history.memo</code>.
     */
    public void setMemo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>activity.action_history.memo</code>.
     */
    public String getMemo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>activity.action_history.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>activity.action_history.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>activity.action_history.created_by</code>.
     */
    public void setCreatedBy(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>activity.action_history.created_by</code>.
     */
    public Integer getCreatedBy() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, String, Timestamp, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, String, Timestamp, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ActionHistory.ACTION_HISTORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ActionHistory.ACTION_HISTORY.AXTENAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ActionHistory.ACTION_HISTORY.ACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ActionHistory.ACTION_HISTORY.MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return ActionHistory.ACTION_HISTORY.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ActionHistory.ACTION_HISTORY.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getAxtenalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAxtenalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionHistoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionHistoryRecord value2(Integer value) {
        setAxtenalId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionHistoryRecord value3(Integer value) {
        setAction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionHistoryRecord value4(String value) {
        setMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionHistoryRecord value5(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionHistoryRecord value6(Integer value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionHistoryRecord values(Integer value1, Integer value2, Integer value3, String value4, Timestamp value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActionHistoryRecord
     */
    public ActionHistoryRecord() {
        super(ActionHistory.ACTION_HISTORY);
    }

    /**
     * Create a detached, initialised ActionHistoryRecord
     */
    public ActionHistoryRecord(Integer id, Integer axtenalId, Integer action, String memo, Timestamp created, Integer createdBy) {
        super(ActionHistory.ACTION_HISTORY);

        set(0, id);
        set(1, axtenalId);
        set(2, action);
        set(3, memo);
        set(4, created);
        set(5, createdBy);
    }
}
