/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.records;


import com.kylin.activity.databases.tables.PriceHistory;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 缴费历史
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PriceHistoryRecord extends UpdatableRecordImpl<PriceHistoryRecord> implements Record8<Integer, Integer, Integer, Integer, Long, Timestamp, Integer, String> {

    private static final long serialVersionUID = 1015920754;

    /**
     * Setter for <code>activity.price_history.id</code>. 编号
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>activity.price_history.id</code>. 编号
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>activity.price_history.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>activity.price_history.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>activity.price_history.activity_id</code>.
     */
    public void setActivityId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>activity.price_history.activity_id</code>.
     */
    public Integer getActivityId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>activity.price_history.activity_ticket_id</code>.
     */
    public void setActivityTicketId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>activity.price_history.activity_ticket_id</code>.
     */
    public Integer getActivityTicketId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>activity.price_history.amount</code>.
     */
    public void setAmount(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>activity.price_history.amount</code>.
     */
    public Long getAmount() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>activity.price_history.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>activity.price_history.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>activity.price_history.created_by</code>. 缴费人
     */
    public void setCreatedBy(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>activity.price_history.created_by</code>. 缴费人
     */
    public Integer getCreatedBy() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>activity.price_history.memo</code>. 缴费说明
     */
    public void setMemo(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>activity.price_history.memo</code>. 缴费说明
     */
    public String getMemo() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, Long, Timestamp, Integer, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, Long, Timestamp, Integer, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PriceHistory.PRICE_HISTORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PriceHistory.PRICE_HISTORY.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return PriceHistory.PRICE_HISTORY.ACTIVITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PriceHistory.PRICE_HISTORY.ACTIVITY_TICKET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return PriceHistory.PRICE_HISTORY.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return PriceHistory.PRICE_HISTORY.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return PriceHistory.PRICE_HISTORY.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return PriceHistory.PRICE_HISTORY.MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getActivityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getActivityTicketId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getActivityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getActivityTicketId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PriceHistoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PriceHistoryRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PriceHistoryRecord value3(Integer value) {
        setActivityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PriceHistoryRecord value4(Integer value) {
        setActivityTicketId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PriceHistoryRecord value5(Long value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PriceHistoryRecord value6(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PriceHistoryRecord value7(Integer value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PriceHistoryRecord value8(String value) {
        setMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PriceHistoryRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Long value5, Timestamp value6, Integer value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PriceHistoryRecord
     */
    public PriceHistoryRecord() {
        super(PriceHistory.PRICE_HISTORY);
    }

    /**
     * Create a detached, initialised PriceHistoryRecord
     */
    public PriceHistoryRecord(Integer id, Integer userId, Integer activityId, Integer activityTicketId, Long amount, Timestamp created, Integer createdBy, String memo) {
        super(PriceHistory.PRICE_HISTORY);

        set(0, id);
        set(1, userId);
        set(2, activityId);
        set(3, activityTicketId);
        set(4, amount);
        set(5, created);
        set(6, createdBy);
        set(7, memo);
    }
}
