/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.records;


import com.kylin.activity.databases.tables.TrainingCamp;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 训练营
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrainingCampRecord extends UpdatableRecordImpl<TrainingCampRecord> implements Record6<Integer, String, String, Timestamp, Integer, Integer> {

    private static final long serialVersionUID = -21322249;

    /**
     * Setter for <code>training_camp.id</code>. 编号
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>training_camp.id</code>. 编号
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>training_camp.camp_name</code>. 训练营名称
     */
    public void setCampName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>training_camp.camp_name</code>. 训练营名称
     */
    public String getCampName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>training_camp.camp_note</code>. 训练营备注
     */
    public void setCampNote(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>training_camp.camp_note</code>. 训练营备注
     */
    public String getCampNote() {
        return (String) get(2);
    }

    /**
     * Setter for <code>training_camp.modified</code>. 编辑时间
     */
    public void setModified(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>training_camp.modified</code>. 编辑时间
     */
    public Timestamp getModified() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>training_camp.modified_by</code>. 编辑用户编号
     */
    public void setModifiedBy(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>training_camp.modified_by</code>. 编辑用户编号
     */
    public Integer getModifiedBy() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>training_camp.community_id</code>. 团体组织编号
     */
    public void setCommunityId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>training_camp.community_id</code>. 团体组织编号
     */
    public Integer getCommunityId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Timestamp, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Timestamp, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TrainingCamp.TRAINING_CAMP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TrainingCamp.TRAINING_CAMP.CAMP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TrainingCamp.TRAINING_CAMP.CAMP_NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TrainingCamp.TRAINING_CAMP.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TrainingCamp.TRAINING_CAMP.MODIFIED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TrainingCamp.TRAINING_CAMP.COMMUNITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCampName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCampNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getCommunityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCampName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCampNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getCommunityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainingCampRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainingCampRecord value2(String value) {
        setCampName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainingCampRecord value3(String value) {
        setCampNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainingCampRecord value4(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainingCampRecord value5(Integer value) {
        setModifiedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainingCampRecord value6(Integer value) {
        setCommunityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainingCampRecord values(Integer value1, String value2, String value3, Timestamp value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrainingCampRecord
     */
    public TrainingCampRecord() {
        super(TrainingCamp.TRAINING_CAMP);
    }

    /**
     * Create a detached, initialised TrainingCampRecord
     */
    public TrainingCampRecord(Integer id, String campName, String campNote, Timestamp modified, Integer modifiedBy, Integer communityId) {
        super(TrainingCamp.TRAINING_CAMP);

        set(0, id);
        set(1, campName);
        set(2, campNote);
        set(3, modified);
        set(4, modifiedBy);
        set(5, communityId);
    }
}
