/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.records;


import com.kylin.activity.databases.tables.VTrainingcamppeople;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VTrainingcamppeopleRecord extends TableRecordImpl<VTrainingcamppeopleRecord> implements Record4<String, String, Long, Long> {

    private static final long serialVersionUID = 2098201542;

    /**
     * Setter for <code>v_TrainingCampPeople.communityName</code>. 社团名称
     */
    public void setCommunityname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>v_TrainingCampPeople.communityName</code>. 社团名称
     */
    public String getCommunityname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>v_TrainingCampPeople.campName</code>. 训练营名称
     */
    public void setCampname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>v_TrainingCampPeople.campName</code>. 训练营名称
     */
    public String getCampname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>v_TrainingCampPeople.attendPeopleCount</code>.
     */
    public void setAttendpeoplecount(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>v_TrainingCampPeople.attendPeopleCount</code>.
     */
    public Long getAttendpeoplecount() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>v_TrainingCampPeople.checkPeopleCount</code>.
     */
    public void setCheckpeoplecount(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>v_TrainingCampPeople.checkPeopleCount</code>.
     */
    public Long getCheckpeoplecount() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Long, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return VTrainingcamppeople.V_TRAININGCAMPPEOPLE.COMMUNITYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VTrainingcamppeople.V_TRAININGCAMPPEOPLE.CAMPNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return VTrainingcamppeople.V_TRAININGCAMPPEOPLE.ATTENDPEOPLECOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return VTrainingcamppeople.V_TRAININGCAMPPEOPLE.CHECKPEOPLECOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getCommunityname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCampname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getAttendpeoplecount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getCheckpeoplecount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCommunityname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCampname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getAttendpeoplecount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getCheckpeoplecount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VTrainingcamppeopleRecord value1(String value) {
        setCommunityname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VTrainingcamppeopleRecord value2(String value) {
        setCampname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VTrainingcamppeopleRecord value3(Long value) {
        setAttendpeoplecount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VTrainingcamppeopleRecord value4(Long value) {
        setCheckpeoplecount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VTrainingcamppeopleRecord values(String value1, String value2, Long value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VTrainingcamppeopleRecord
     */
    public VTrainingcamppeopleRecord() {
        super(VTrainingcamppeople.V_TRAININGCAMPPEOPLE);
    }

    /**
     * Create a detached, initialised VTrainingcamppeopleRecord
     */
    public VTrainingcamppeopleRecord(String communityname, String campname, Long attendpeoplecount, Long checkpeoplecount) {
        super(VTrainingcamppeople.V_TRAININGCAMPPEOPLE);

        set(0, communityname);
        set(1, campname);
        set(2, attendpeoplecount);
        set(3, checkpeoplecount);
    }
}
