/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.daos;


import com.kylin.activity.databases.tables.ActivityUserRecord;
import com.kylin.activity.databases.tables.records.ActivityUserRecordRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.List;


/**
 * 用户报名活动打卡记录表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ActivityUserRecordDao extends DAOImpl<ActivityUserRecordRecord, com.kylin.activity.databases.tables.pojos.ActivityUserRecord, Integer> {

    /**
     * Create a new ActivityUserRecordDao without any configuration
     */
    public ActivityUserRecordDao() {
        super(ActivityUserRecord.ACTIVITY_USER_RECORD, com.kylin.activity.databases.tables.pojos.ActivityUserRecord.class);
    }

    /**
     * Create a new ActivityUserRecordDao with an attached configuration
     */
    @Autowired
    public ActivityUserRecordDao(Configuration configuration) {
        super(ActivityUserRecord.ACTIVITY_USER_RECORD, com.kylin.activity.databases.tables.pojos.ActivityUserRecord.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.kylin.activity.databases.tables.pojos.ActivityUserRecord object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityUserRecord> fetchById(Integer... values) {
        return fetch(ActivityUserRecord.ACTIVITY_USER_RECORD.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.kylin.activity.databases.tables.pojos.ActivityUserRecord fetchOneById(Integer value) {
        return fetchOne(ActivityUserRecord.ACTIVITY_USER_RECORD.ID, value);
    }

    /**
     * Fetch records that have <code>activity_user_id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityUserRecord> fetchByActivityUserId(Integer... values) {
        return fetch(ActivityUserRecord.ACTIVITY_USER_RECORD.ACTIVITY_USER_ID, values);
    }

    /**
     * Fetch records that have <code>record_time IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityUserRecord> fetchByRecordTime(Timestamp... values) {
        return fetch(ActivityUserRecord.ACTIVITY_USER_RECORD.RECORD_TIME, values);
    }

    /**
     * Fetch records that have <code>pictures IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityUserRecord> fetchByPictures(String... values) {
        return fetch(ActivityUserRecord.ACTIVITY_USER_RECORD.PICTURES, values);
    }

    /**
     * Fetch records that have <code>notes IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityUserRecord> fetchByNotes(String... values) {
        return fetch(ActivityUserRecord.ACTIVITY_USER_RECORD.NOTES, values);
    }
}
