/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.daos;


import com.kylin.activity.databases.tables.ActivityPhotoPicture;
import com.kylin.activity.databases.tables.records.ActivityPhotoPictureRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 图片集
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ActivityPhotoPictureDao extends DAOImpl<ActivityPhotoPictureRecord, com.kylin.activity.databases.tables.pojos.ActivityPhotoPicture, Integer> {

    /**
     * Create a new ActivityPhotoPictureDao without any configuration
     */
    public ActivityPhotoPictureDao() {
        super(ActivityPhotoPicture.ACTIVITY_PHOTO_PICTURE, com.kylin.activity.databases.tables.pojos.ActivityPhotoPicture.class);
    }

    /**
     * Create a new ActivityPhotoPictureDao with an attached configuration
     */
    @Autowired
    public ActivityPhotoPictureDao(Configuration configuration) {
        super(ActivityPhotoPicture.ACTIVITY_PHOTO_PICTURE, com.kylin.activity.databases.tables.pojos.ActivityPhotoPicture.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.kylin.activity.databases.tables.pojos.ActivityPhotoPicture object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityPhotoPicture> fetchById(Integer... values) {
        return fetch(ActivityPhotoPicture.ACTIVITY_PHOTO_PICTURE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.kylin.activity.databases.tables.pojos.ActivityPhotoPicture fetchOneById(Integer value) {
        return fetchOne(ActivityPhotoPicture.ACTIVITY_PHOTO_PICTURE.ID, value);
    }

    /**
     * Fetch records that have <code>activity_photo_id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityPhotoPicture> fetchByActivityPhotoId(Integer... values) {
        return fetch(ActivityPhotoPicture.ACTIVITY_PHOTO_PICTURE.ACTIVITY_PHOTO_ID, values);
    }

    /**
     * Fetch records that have <code>picture IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityPhotoPicture> fetchByPicture(String... values) {
        return fetch(ActivityPhotoPicture.ACTIVITY_PHOTO_PICTURE.PICTURE, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityPhotoPicture> fetchByCreated(Timestamp... values) {
        return fetch(ActivityPhotoPicture.ACTIVITY_PHOTO_PICTURE.CREATED, values);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityPhotoPicture> fetchByCreatedBy(Integer... values) {
        return fetch(ActivityPhotoPicture.ACTIVITY_PHOTO_PICTURE.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>order IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityPhotoPicture> fetchByOrder(Integer... values) {
        return fetch(ActivityPhotoPicture.ACTIVITY_PHOTO_PICTURE.ORDER, values);
    }
}
