/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.daos;


import com.kylin.activity.databases.tables.ActivityTicket;
import com.kylin.activity.databases.tables.records.ActivityTicketRecord;

import java.math.BigDecimal;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 活动门票
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ActivityTicketDao extends DAOImpl<ActivityTicketRecord, com.kylin.activity.databases.tables.pojos.ActivityTicket, Integer> {

    /**
     * Create a new ActivityTicketDao without any configuration
     */
    public ActivityTicketDao() {
        super(ActivityTicket.ACTIVITY_TICKET, com.kylin.activity.databases.tables.pojos.ActivityTicket.class);
    }

    /**
     * Create a new ActivityTicketDao with an attached configuration
     */
    @Autowired
    public ActivityTicketDao(Configuration configuration) {
        super(ActivityTicket.ACTIVITY_TICKET, com.kylin.activity.databases.tables.pojos.ActivityTicket.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.kylin.activity.databases.tables.pojos.ActivityTicket object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityTicket> fetchById(Integer... values) {
        return fetch(ActivityTicket.ACTIVITY_TICKET.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.kylin.activity.databases.tables.pojos.ActivityTicket fetchOneById(Integer value) {
        return fetchOne(ActivityTicket.ACTIVITY_TICKET.ID, value);
    }

    /**
     * Fetch records that have <code>activity_id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityTicket> fetchByActivityId(Integer... values) {
        return fetch(ActivityTicket.ACTIVITY_TICKET.ACTIVITY_ID, values);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityTicket> fetchByTitle(String... values) {
        return fetch(ActivityTicket.ACTIVITY_TICKET.TITLE, values);
    }

    /**
     * Fetch records that have <code>memo IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityTicket> fetchByMemo(String... values) {
        return fetch(ActivityTicket.ACTIVITY_TICKET.MEMO, values);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityTicket> fetchByPrice(BigDecimal... values) {
        return fetch(ActivityTicket.ACTIVITY_TICKET.PRICE, values);
    }

    /**
     * Fetch records that have <code>count IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityTicket> fetchByCount(Integer... values) {
        return fetch(ActivityTicket.ACTIVITY_TICKET.COUNT, values);
    }

    /**
     * Fetch records that have <code>user_level IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityTicket> fetchByUserLevel(Integer... values) {
        return fetch(ActivityTicket.ACTIVITY_TICKET.USER_LEVEL, values);
    }

    /**
     * Fetch records that have <code>score IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ActivityTicket> fetchByScore(Integer... values) {
        return fetch(ActivityTicket.ACTIVITY_TICKET.SCORE, values);
    }
}
