/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.daos;


import com.kylin.activity.databases.tables.CommunityUser;
import com.kylin.activity.databases.tables.records.CommunityUserRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 社团成员
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class CommunityUserDao extends DAOImpl<CommunityUserRecord, com.kylin.activity.databases.tables.pojos.CommunityUser, Integer> {

    /**
     * Create a new CommunityUserDao without any configuration
     */
    public CommunityUserDao() {
        super(CommunityUser.COMMUNITY_USER, com.kylin.activity.databases.tables.pojos.CommunityUser.class);
    }

    /**
     * Create a new CommunityUserDao with an attached configuration
     */
    @Autowired
    public CommunityUserDao(Configuration configuration) {
        super(CommunityUser.COMMUNITY_USER, com.kylin.activity.databases.tables.pojos.CommunityUser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.kylin.activity.databases.tables.pojos.CommunityUser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.CommunityUser> fetchById(Integer... values) {
        return fetch(CommunityUser.COMMUNITY_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.kylin.activity.databases.tables.pojos.CommunityUser fetchOneById(Integer value) {
        return fetchOne(CommunityUser.COMMUNITY_USER.ID, value);
    }

    /**
     * Fetch records that have <code>community_id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.CommunityUser> fetchByCommunityId(Integer... values) {
        return fetch(CommunityUser.COMMUNITY_USER.COMMUNITY_ID, values);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.CommunityUser> fetchByUserId(Integer... values) {
        return fetch(CommunityUser.COMMUNITY_USER.USER_ID, values);
    }

    /**
     * Fetch records that have <code>role IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.CommunityUser> fetchByRole(String... values) {
        return fetch(CommunityUser.COMMUNITY_USER.ROLE, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.CommunityUser> fetchByCreated(Timestamp... values) {
        return fetch(CommunityUser.COMMUNITY_USER.CREATED, values);
    }

    /**
     * Fetch records that have <code>level IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.CommunityUser> fetchByLevel(Integer... values) {
        return fetch(CommunityUser.COMMUNITY_USER.LEVEL, values);
    }

    /**
     * Fetch records that have <code>is_black IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.CommunityUser> fetchByIsBlack(Boolean... values) {
        return fetch(CommunityUser.COMMUNITY_USER.IS_BLACK, values);
    }
}
