/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.daos;


import com.kylin.activity.databases.tables.MaterialLibrary;
import com.kylin.activity.databases.tables.records.MaterialLibraryRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class MaterialLibraryDao extends DAOImpl<MaterialLibraryRecord, com.kylin.activity.databases.tables.pojos.MaterialLibrary, Integer> {

    /**
     * Create a new MaterialLibraryDao without any configuration
     */
    public MaterialLibraryDao() {
        super(MaterialLibrary.MATERIAL_LIBRARY, com.kylin.activity.databases.tables.pojos.MaterialLibrary.class);
    }

    /**
     * Create a new MaterialLibraryDao with an attached configuration
     */
    @Autowired
    public MaterialLibraryDao(Configuration configuration) {
        super(MaterialLibrary.MATERIAL_LIBRARY, com.kylin.activity.databases.tables.pojos.MaterialLibrary.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.kylin.activity.databases.tables.pojos.MaterialLibrary object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.MaterialLibrary> fetchById(Integer... values) {
        return fetch(MaterialLibrary.MATERIAL_LIBRARY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.kylin.activity.databases.tables.pojos.MaterialLibrary fetchOneById(Integer value) {
        return fetchOne(MaterialLibrary.MATERIAL_LIBRARY.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.MaterialLibrary> fetchByName(String... values) {
        return fetch(MaterialLibrary.MATERIAL_LIBRARY.NAME, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.MaterialLibrary> fetchByCreated(Timestamp... values) {
        return fetch(MaterialLibrary.MATERIAL_LIBRARY.CREATED, values);
    }

    /**
     * Fetch records that have <code>sequence IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.MaterialLibrary> fetchBySequence(Integer... values) {
        return fetch(MaterialLibrary.MATERIAL_LIBRARY.SEQUENCE, values);
    }

    /**
     * Fetch records that have <code>category IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.MaterialLibrary> fetchByCategory(String... values) {
        return fetch(MaterialLibrary.MATERIAL_LIBRARY.CATEGORY, values);
    }
}
