/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.daos;


import com.kylin.activity.databases.tables.Poster;
import com.kylin.activity.databases.tables.records.PosterRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.List;


/**
 * 海报表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class PosterDao extends DAOImpl<PosterRecord, com.kylin.activity.databases.tables.pojos.Poster, Integer> {

    /**
     * Create a new PosterDao without any configuration
     */
    public PosterDao() {
        super(Poster.POSTER, com.kylin.activity.databases.tables.pojos.Poster.class);
    }

    /**
     * Create a new PosterDao with an attached configuration
     */
    @Autowired
    public PosterDao(Configuration configuration) {
        super(Poster.POSTER, com.kylin.activity.databases.tables.pojos.Poster.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.kylin.activity.databases.tables.pojos.Poster object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.Poster> fetchById(Integer... values) {
        return fetch(Poster.POSTER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.kylin.activity.databases.tables.pojos.Poster fetchOneById(Integer value) {
        return fetchOne(Poster.POSTER.ID, value);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.Poster> fetchByTitle(String... values) {
        return fetch(Poster.POSTER.TITLE, values);
    }

    /**
     * Fetch records that have <code>avatar IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.Poster> fetchByAvatar(String... values) {
        return fetch(Poster.POSTER.AVATAR, values);
    }

    /**
     * Fetch records that have <code>mobile_avatar IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.Poster> fetchByMobileAvatar(String... values) {
        return fetch(Poster.POSTER.MOBILE_AVATAR, values);
    }

    /**
     * Fetch records that have <code>link IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.Poster> fetchByLink(String... values) {
        return fetch(Poster.POSTER.LINK, values);
    }

    /**
     * Fetch records that have <code>activity_id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.Poster> fetchByActivityId(Integer... values) {
        return fetch(Poster.POSTER.ACTIVITY_ID, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.Poster> fetchByCreated(Timestamp... values) {
        return fetch(Poster.POSTER.CREATED, values);
    }

    /**
     * Fetch records that have <code>poster_type IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.Poster> fetchByPosterType(String... values) {
        return fetch(Poster.POSTER.POSTER_TYPE, values);
    }

    /**
     * Fetch records that have <code>show IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.Poster> fetchByShow(Boolean... values) {
        return fetch(Poster.POSTER.SHOW, values);
    }

    /**
     * Fetch records that have <code>sequence IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.Poster> fetchBySequence(Integer... values) {
        return fetch(Poster.POSTER.SEQUENCE, values);
    }
}
