/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.daos;


import com.kylin.activity.databases.tables.PriceHistory;
import com.kylin.activity.databases.tables.records.PriceHistoryRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 缴费历史
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class PriceHistoryDao extends DAOImpl<PriceHistoryRecord, com.kylin.activity.databases.tables.pojos.PriceHistory, Integer> {

    /**
     * Create a new PriceHistoryDao without any configuration
     */
    public PriceHistoryDao() {
        super(PriceHistory.PRICE_HISTORY, com.kylin.activity.databases.tables.pojos.PriceHistory.class);
    }

    /**
     * Create a new PriceHistoryDao with an attached configuration
     */
    @Autowired
    public PriceHistoryDao(Configuration configuration) {
        super(PriceHistory.PRICE_HISTORY, com.kylin.activity.databases.tables.pojos.PriceHistory.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.kylin.activity.databases.tables.pojos.PriceHistory object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.PriceHistory> fetchById(Integer... values) {
        return fetch(PriceHistory.PRICE_HISTORY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.kylin.activity.databases.tables.pojos.PriceHistory fetchOneById(Integer value) {
        return fetchOne(PriceHistory.PRICE_HISTORY.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.PriceHistory> fetchByUserId(Integer... values) {
        return fetch(PriceHistory.PRICE_HISTORY.USER_ID, values);
    }

    /**
     * Fetch records that have <code>activity_id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.PriceHistory> fetchByActivityId(Integer... values) {
        return fetch(PriceHistory.PRICE_HISTORY.ACTIVITY_ID, values);
    }

    /**
     * Fetch records that have <code>activity_ticket_id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.PriceHistory> fetchByActivityTicketId(Integer... values) {
        return fetch(PriceHistory.PRICE_HISTORY.ACTIVITY_TICKET_ID, values);
    }

    /**
     * Fetch records that have <code>amount IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.PriceHistory> fetchByAmount(Long... values) {
        return fetch(PriceHistory.PRICE_HISTORY.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.PriceHistory> fetchByCreated(Timestamp... values) {
        return fetch(PriceHistory.PRICE_HISTORY.CREATED, values);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.PriceHistory> fetchByCreatedBy(Integer... values) {
        return fetch(PriceHistory.PRICE_HISTORY.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>memo IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.PriceHistory> fetchByMemo(String... values) {
        return fetch(PriceHistory.PRICE_HISTORY.MEMO, values);
    }
}
