/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.daos;


import com.kylin.activity.databases.tables.ScoreHistory;
import com.kylin.activity.databases.tables.records.ScoreHistoryRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 积分历史
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ScoreHistoryDao extends DAOImpl<ScoreHistoryRecord, com.kylin.activity.databases.tables.pojos.ScoreHistory, Integer> {

    /**
     * Create a new ScoreHistoryDao without any configuration
     */
    public ScoreHistoryDao() {
        super(ScoreHistory.SCORE_HISTORY, com.kylin.activity.databases.tables.pojos.ScoreHistory.class);
    }

    /**
     * Create a new ScoreHistoryDao with an attached configuration
     */
    @Autowired
    public ScoreHistoryDao(Configuration configuration) {
        super(ScoreHistory.SCORE_HISTORY, com.kylin.activity.databases.tables.pojos.ScoreHistory.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.kylin.activity.databases.tables.pojos.ScoreHistory object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ScoreHistory> fetchById(Integer... values) {
        return fetch(ScoreHistory.SCORE_HISTORY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.kylin.activity.databases.tables.pojos.ScoreHistory fetchOneById(Integer value) {
        return fetchOne(ScoreHistory.SCORE_HISTORY.ID, value);
    }

    /**
     * Fetch records that have <code>score IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ScoreHistory> fetchByScore(Integer... values) {
        return fetch(ScoreHistory.SCORE_HISTORY.SCORE, values);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ScoreHistory> fetchByUserId(Integer... values) {
        return fetch(ScoreHistory.SCORE_HISTORY.USER_ID, values);
    }

    /**
     * Fetch records that have <code>activity_id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ScoreHistory> fetchByActivityId(Integer... values) {
        return fetch(ScoreHistory.SCORE_HISTORY.ACTIVITY_ID, values);
    }

    /**
     * Fetch records that have <code>memo IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ScoreHistory> fetchByMemo(String... values) {
        return fetch(ScoreHistory.SCORE_HISTORY.MEMO, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ScoreHistory> fetchByCreated(Timestamp... values) {
        return fetch(ScoreHistory.SCORE_HISTORY.CREATED, values);
    }

    /**
     * Fetch records that have <code>community_id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.ScoreHistory> fetchByCommunityId(Integer... values) {
        return fetch(ScoreHistory.SCORE_HISTORY.COMMUNITY_ID, values);
    }
}
