/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables.daos;


import com.kylin.activity.databases.tables.TrainingCamp;
import com.kylin.activity.databases.tables.records.TrainingCampRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TrainingCampDao extends DAOImpl<TrainingCampRecord, com.kylin.activity.databases.tables.pojos.TrainingCamp, Integer> {

    /**
     * Create a new TrainingCampDao without any configuration
     */
    public TrainingCampDao() {
        super(TrainingCamp.TRAINING_CAMP, com.kylin.activity.databases.tables.pojos.TrainingCamp.class);
    }

    /**
     * Create a new TrainingCampDao with an attached configuration
     */
    @Autowired
    public TrainingCampDao(Configuration configuration) {
        super(TrainingCamp.TRAINING_CAMP, com.kylin.activity.databases.tables.pojos.TrainingCamp.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.kylin.activity.databases.tables.pojos.TrainingCamp object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.TrainingCamp> fetchById(Integer... values) {
        return fetch(TrainingCamp.TRAINING_CAMP.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.kylin.activity.databases.tables.pojos.TrainingCamp fetchOneById(Integer value) {
        return fetchOne(TrainingCamp.TRAINING_CAMP.ID, value);
    }

    /**
     * Fetch records that have <code>camp_name IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.TrainingCamp> fetchByCampName(String... values) {
        return fetch(TrainingCamp.TRAINING_CAMP.CAMP_NAME, values);
    }

    /**
     * Fetch records that have <code>camp_note IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.TrainingCamp> fetchByCampNote(String... values) {
        return fetch(TrainingCamp.TRAINING_CAMP.CAMP_NOTE, values);
    }

    /**
     * Fetch records that have <code>modified IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.TrainingCamp> fetchByModified(Timestamp... values) {
        return fetch(TrainingCamp.TRAINING_CAMP.MODIFIED, values);
    }

    /**
     * Fetch records that have <code>modified_by IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.TrainingCamp> fetchByModifiedBy(Integer... values) {
        return fetch(TrainingCamp.TRAINING_CAMP.MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>community_id IN (values)</code>
     */
    public List<com.kylin.activity.databases.tables.pojos.TrainingCamp> fetchByCommunityId(Integer... values) {
        return fetch(TrainingCamp.TRAINING_CAMP.COMMUNITY_ID, values);
    }
}
