/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases;


import com.kylin.activity.databases.tables.ActionHistory;
import com.kylin.activity.databases.tables.ActivityFavorite;
import com.kylin.activity.databases.tables.ActivityTicket;
import com.kylin.activity.databases.tables.ActivityUser;
import com.kylin.activity.databases.tables.Company;
import com.kylin.activity.databases.tables.Parameter;
import com.kylin.activity.databases.tables.PayOrder;
import com.kylin.activity.databases.tables.PriceHistory;
import com.kylin.activity.databases.tables.ScoreHistory;
import com.kylin.activity.databases.tables.User;
import com.kylin.activity.databases.tables.Vercode;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Activity extends SchemaImpl {

    private static final long serialVersionUID = -1367707359;

    /**
     * The reference instance of <code>activity</code>
     */
    public static final Activity ACTIVITY = new Activity();

    /**
     * The table <code>activity.action_history</code>.
     */
    public final ActionHistory ACTION_HISTORY = com.kylin.activity.databases.tables.ActionHistory.ACTION_HISTORY;

    /**
     * 活动
     */
    public final com.kylin.activity.databases.tables.Activity ACTIVITY_ = com.kylin.activity.databases.tables.Activity.ACTIVITY_;

    /**
     * 我喜欢的活动列表
     */
    public final ActivityFavorite ACTIVITY_FAVORITE = com.kylin.activity.databases.tables.ActivityFavorite.ACTIVITY_FAVORITE;

    /**
     * 活动门票
     */
    public final ActivityTicket ACTIVITY_TICKET = com.kylin.activity.databases.tables.ActivityTicket.ACTIVITY_TICKET;

    /**
     * 参与活动人
     */
    public final ActivityUser ACTIVITY_USER = com.kylin.activity.databases.tables.ActivityUser.ACTIVITY_USER;

    /**
     * 单位公司
     */
    public final Company COMPANY = com.kylin.activity.databases.tables.Company.COMPANY;

    /**
     * 字典参数
     */
    public final Parameter PARAMETER = com.kylin.activity.databases.tables.Parameter.PARAMETER;

    /**
     * The table <code>activity.pay_order</code>.
     */
    public final PayOrder PAY_ORDER = com.kylin.activity.databases.tables.PayOrder.PAY_ORDER;

    /**
     * 缴费历史
     */
    public final PriceHistory PRICE_HISTORY = com.kylin.activity.databases.tables.PriceHistory.PRICE_HISTORY;

    /**
     * 积分历史
     */
    public final ScoreHistory SCORE_HISTORY = com.kylin.activity.databases.tables.ScoreHistory.SCORE_HISTORY;

    /**
     * 用户表
     */
    public final User USER = com.kylin.activity.databases.tables.User.USER;

    /**
     * 验证码
     */
    public final Vercode VERCODE = com.kylin.activity.databases.tables.Vercode.VERCODE;

    /**
     * No further instances allowed
     */
    private Activity() {
        super("activity", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ActionHistory.ACTION_HISTORY,
            com.kylin.activity.databases.tables.Activity.ACTIVITY_,
            ActivityFavorite.ACTIVITY_FAVORITE,
            ActivityTicket.ACTIVITY_TICKET,
            ActivityUser.ACTIVITY_USER,
            Company.COMPANY,
            Parameter.PARAMETER,
            PayOrder.PAY_ORDER,
            PriceHistory.PRICE_HISTORY,
            ScoreHistory.SCORE_HISTORY,
            User.USER,
            Vercode.VERCODE);
    }
}
