/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases;


import com.kylin.activity.databases.tables.ActionHistory;
import com.kylin.activity.databases.tables.Activity;
import com.kylin.activity.databases.tables.ActivityFavorite;
import com.kylin.activity.databases.tables.ActivityTicket;
import com.kylin.activity.databases.tables.ActivityUser;
import com.kylin.activity.databases.tables.Company;
import com.kylin.activity.databases.tables.PayOrder;
import com.kylin.activity.databases.tables.PriceHistory;
import com.kylin.activity.databases.tables.ScoreHistory;
import com.kylin.activity.databases.tables.User;
import com.kylin.activity.databases.tables.Vercode;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>activity</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACTION_HISTORY_PRIMARY = Indexes0.ACTION_HISTORY_PRIMARY;
    public static final Index ACTIVITY_PRIMARY = Indexes0.ACTIVITY_PRIMARY;
    public static final Index ACTIVITY_FAVORITE_PRIMARY = Indexes0.ACTIVITY_FAVORITE_PRIMARY;
    public static final Index ACTIVITY_TICKET_PRIMARY = Indexes0.ACTIVITY_TICKET_PRIMARY;
    public static final Index ACTIVITY_USER_PRIMARY = Indexes0.ACTIVITY_USER_PRIMARY;
    public static final Index COMPANY_PRIMARY = Indexes0.COMPANY_PRIMARY;
    public static final Index PAY_ORDER_PRIMARY = Indexes0.PAY_ORDER_PRIMARY;
    public static final Index PRICE_HISTORY_PRIMARY = Indexes0.PRICE_HISTORY_PRIMARY;
    public static final Index SCORE_HISTORY_PRIMARY = Indexes0.SCORE_HISTORY_PRIMARY;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USER_UK_USERNAME = Indexes0.USER_UK_USERNAME;
    public static final Index VERCODE_PRIMARY = Indexes0.VERCODE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index ACTION_HISTORY_PRIMARY = createIndex("PRIMARY", ActionHistory.ACTION_HISTORY, new OrderField[] { ActionHistory.ACTION_HISTORY.ID }, true);
        public static Index ACTIVITY_PRIMARY = createIndex("PRIMARY", Activity.ACTIVITY_, new OrderField[] { Activity.ACTIVITY_.ID }, true);
        public static Index ACTIVITY_FAVORITE_PRIMARY = createIndex("PRIMARY", ActivityFavorite.ACTIVITY_FAVORITE, new OrderField[] { ActivityFavorite.ACTIVITY_FAVORITE.ID }, true);
        public static Index ACTIVITY_TICKET_PRIMARY = createIndex("PRIMARY", ActivityTicket.ACTIVITY_TICKET, new OrderField[] { ActivityTicket.ACTIVITY_TICKET.ID }, true);
        public static Index ACTIVITY_USER_PRIMARY = createIndex("PRIMARY", ActivityUser.ACTIVITY_USER, new OrderField[] { ActivityUser.ACTIVITY_USER.ID }, true);
        public static Index COMPANY_PRIMARY = createIndex("PRIMARY", Company.COMPANY, new OrderField[] { Company.COMPANY.ID }, true);
        public static Index PAY_ORDER_PRIMARY = createIndex("PRIMARY", PayOrder.PAY_ORDER, new OrderField[] { PayOrder.PAY_ORDER.ID }, true);
        public static Index PRICE_HISTORY_PRIMARY = createIndex("PRIMARY", PriceHistory.PRICE_HISTORY, new OrderField[] { PriceHistory.PRICE_HISTORY.ID }, true);
        public static Index SCORE_HISTORY_PRIMARY = createIndex("PRIMARY", ScoreHistory.SCORE_HISTORY, new OrderField[] { ScoreHistory.SCORE_HISTORY.ID }, true);
        public static Index USER_PRIMARY = createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_UK_USERNAME = createIndex("uk_username", User.USER, new OrderField[] { User.USER.USERNAME }, true);
        public static Index VERCODE_PRIMARY = createIndex("PRIMARY", Vercode.VERCODE, new OrderField[] { Vercode.VERCODE.ID }, true);
    }
}
