/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables;


import com.kylin.activity.databases.Activityv2;
import com.kylin.activity.databases.Indexes;
import com.kylin.activity.databases.Keys;
import com.kylin.activity.databases.tables.records.ActivityPhotoPictureRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 图片集
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityPhotoPicture extends TableImpl<ActivityPhotoPictureRecord> {

    private static final long serialVersionUID = -648559933;

    /**
     * The reference instance of <code>activityv2.activity_photo_picture</code>
     */
    public static final ActivityPhotoPicture ACTIVITY_PHOTO_PICTURE = new ActivityPhotoPicture();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActivityPhotoPictureRecord> getRecordType() {
        return ActivityPhotoPictureRecord.class;
    }

    /**
     * The column <code>activityv2.activity_photo_picture.id</code>.
     */
    public final TableField<ActivityPhotoPictureRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>activityv2.activity_photo_picture.activity_photo_id</code>. 关联编号
     */
    public final TableField<ActivityPhotoPictureRecord, Integer> ACTIVITY_PHOTO_ID = createField("activity_photo_id", org.jooq.impl.SQLDataType.INTEGER, this, "关联编号");

    /**
     * The column <code>activityv2.activity_photo_picture.picture</code>. 图片
     */
    public final TableField<ActivityPhotoPictureRecord, String> PICTURE = createField("picture", org.jooq.impl.SQLDataType.VARCHAR(255), this, "图片");

    /**
     * The column <code>activityv2.activity_photo_picture.created</code>.
     */
    public final TableField<ActivityPhotoPictureRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>activityv2.activity_photo_picture.created_by</code>.
     */
    public final TableField<ActivityPhotoPictureRecord, Integer> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>activityv2.activity_photo_picture.order</code>. 排序
     */
    public final TableField<ActivityPhotoPictureRecord, Integer> ORDER = createField("order", org.jooq.impl.SQLDataType.INTEGER, this, "排序");

    /**
     * Create a <code>activityv2.activity_photo_picture</code> table reference
     */
    public ActivityPhotoPicture() {
        this(DSL.name("activity_photo_picture"), null);
    }

    /**
     * Create an aliased <code>activityv2.activity_photo_picture</code> table reference
     */
    public ActivityPhotoPicture(String alias) {
        this(DSL.name(alias), ACTIVITY_PHOTO_PICTURE);
    }

    /**
     * Create an aliased <code>activityv2.activity_photo_picture</code> table reference
     */
    public ActivityPhotoPicture(Name alias) {
        this(alias, ACTIVITY_PHOTO_PICTURE);
    }

    private ActivityPhotoPicture(Name alias, Table<ActivityPhotoPictureRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActivityPhotoPicture(Name alias, Table<ActivityPhotoPictureRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "图片集");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Activityv2.ACTIVITYV2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACTIVITY_PHOTO_PICTURE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ActivityPhotoPictureRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ACTIVITY_PHOTO_PICTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ActivityPhotoPictureRecord> getPrimaryKey() {
        return Keys.KEY_ACTIVITY_PHOTO_PICTURE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ActivityPhotoPictureRecord>> getKeys() {
        return Arrays.<UniqueKey<ActivityPhotoPictureRecord>>asList(Keys.KEY_ACTIVITY_PHOTO_PICTURE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityPhotoPicture as(String alias) {
        return new ActivityPhotoPicture(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityPhotoPicture as(Name alias) {
        return new ActivityPhotoPicture(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivityPhotoPicture rename(String name) {
        return new ActivityPhotoPicture(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivityPhotoPicture rename(Name name) {
        return new ActivityPhotoPicture(name, null);
    }
}
