/*
 * This file is generated by jOOQ.
*/
package com.kylin.activity.databases.tables;


import com.kylin.activity.databases.DefaultSchema;
import com.kylin.activity.databases.tables.records.VTrainingcamppeopleRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VTrainingcamppeople extends TableImpl<VTrainingcamppeopleRecord> {

    private static final long serialVersionUID = 1218391388;

    /**
     * The reference instance of <code>v_TrainingCampPeople</code>
     */
    public static final VTrainingcamppeople V_TRAININGCAMPPEOPLE = new VTrainingcamppeople();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VTrainingcamppeopleRecord> getRecordType() {
        return VTrainingcamppeopleRecord.class;
    }

    /**
     * The column <code>v_TrainingCampPeople.communityName</code>. 社团名称
     */
    public final TableField<VTrainingcamppeopleRecord, String> COMMUNITYNAME = createField("communityName", org.jooq.impl.SQLDataType.VARCHAR(255), this, "社团名称");

    /**
     * The column <code>v_TrainingCampPeople.campName</code>. 训练营名称
     */
    public final TableField<VTrainingcamppeopleRecord, String> CAMPNAME = createField("campName", org.jooq.impl.SQLDataType.VARCHAR(255), this, "训练营名称");

    /**
     * The column <code>v_TrainingCampPeople.attendPeopleCount</code>.
     */
    public final TableField<VTrainingcamppeopleRecord, Long> ATTENDPEOPLECOUNT = createField("attendPeopleCount", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>v_TrainingCampPeople.checkPeopleCount</code>.
     */
    public final TableField<VTrainingcamppeopleRecord, Long> CHECKPEOPLECOUNT = createField("checkPeopleCount", org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * Create a <code>v_TrainingCampPeople</code> table reference
     */
    public VTrainingcamppeople() {
        this(DSL.name("v_TrainingCampPeople"), null);
    }

    /**
     * Create an aliased <code>v_TrainingCampPeople</code> table reference
     */
    public VTrainingcamppeople(String alias) {
        this(DSL.name(alias), V_TRAININGCAMPPEOPLE);
    }

    /**
     * Create an aliased <code>v_TrainingCampPeople</code> table reference
     */
    public VTrainingcamppeople(Name alias) {
        this(alias, V_TRAININGCAMPPEOPLE);
    }

    private VTrainingcamppeople(Name alias, Table<VTrainingcamppeopleRecord> aliased) {
        this(alias, aliased, null);
    }

    private VTrainingcamppeople(Name alias, Table<VTrainingcamppeopleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VTrainingcamppeople as(String alias) {
        return new VTrainingcamppeople(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VTrainingcamppeople as(Name alias) {
        return new VTrainingcamppeople(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VTrainingcamppeople rename(String name) {
        return new VTrainingcamppeople(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VTrainingcamppeople rename(Name name) {
        return new VTrainingcamppeople(name, null);
    }
}
